name: CI for working branch

on: 
  push:
    branches:
      - "**"
    branches-ignore:
      - main
    paths-ignore:
      - 'app/**'


  workflow_dispatch:
  

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  CI:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra

    steps:
        - uses: actions/checkout@v4
          with:
            ref: ${{ github.ref }}
    
        - uses: hashicorp/setup-terraform@v2

        - name: init
          run: terraform init

        - name: validate
          run: terraform validate
