name: CI for webapp

on: 
  push:
    branches:
      - "**"
      - "!main"
    paths:
      - 'app/webapp/**'


  workflow_dispatch:
  

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REGION: "us-east-1"
  ECR_REPO: "justinlim-ecr-repo"

jobs:

  CI:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app/webapp

    steps:
        - uses: actions/checkout@v4
          with:
            ref: ${{ github.ref }}
    
        - name: Docker version
          run: docker --version

