name: CI for merge to main

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/merge-infra.yml'


  workflow_dispatch:

  
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  CI:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra

    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 1
            ref: main
    
        - uses: hashicorp/setup-terraform@v2

        - name: init
          run: terraform init -migrate-state

        - name: validate
          run: terraform validate

        - name: plan
          run: terraform plan


